name: Deploy GitHub Pages

on:
  push:
    branches: [main]
    paths:
      - 'docs/**'

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Copy docs to temp folder
        run: |
          mkdir site
          cp -R docs/* site/

      - name: Switch to gh-pages and deploy
        run: |
          git config user.name "github-actions"
          git config user.email "actions@github.com"
          git checkout --orphan gh-pages
          git reset --hard
          git clean -fdx
          cp -R site/* .
          git add .
          git commit -m "🚀 Deploy to GitHub Pages"
          git remote set-url origin https://x-access-token:${{ secrets.GH_TOKEN }}@github.com/Warlockie999/planogram-ai.git
          git push -f origin gh-pages
